name: Pipeline Revisão

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazendo clone do repo
        uses: actions/checkout@v3

      - name: Configurando python
        uses: actions/setup-python@v4

      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Rodando os testes
        run: pytest
        
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "usr-crfllg08fa8c73d87edg"}' \
            https://api.render.com/v1/services/usr-crfllg08fa8c73d87edg/deploys


      
